import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'models/user_profile.dart';
import 'screens/onboarding_screen.dart';
import 'services/notification_service.dart';
import 'services/simple_reminder_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  try {
    // Initialize Hive with minimal setup to avoid corruption issues
    await Hive.initFlutter();
    
    // Register only essential adapters
    Hive.registerAdapter(UserProfileAdapter());
    // Note: MedicationReminderAdapter will be generated by build_runner
    
    // Initialize notification service first
    try {
      await NotificationService.initialize();
      print('✅ Notification service initialized');
    } catch (e) {
      print('⚠️ Notification service initialization failed: $e');
    }
    
    // Only open essential boxes with clean slate approach
    try {
      await Hive.openBox<UserProfile>('userProfiles');
      print('userProfiles box opened successfully');
    } catch (e) {
      print('Error opening userProfiles box: $e');
      try {
        await Hive.deleteBoxFromDisk('userProfiles');
        await Hive.openBox<UserProfile>('userProfiles');
        print('userProfiles box recreated successfully');
      } catch (e2) {
        print('Failed to recreate userProfiles box: $e2');
      }
    }
    
    try {
      await Hive.openBox('settings');
      print('settings box opened successfully');
    } catch (e) {
      print('Error opening settings box: $e');
      try {
        await Hive.deleteBoxFromDisk('settings');
        await Hive.openBox('settings');
        print('settings box recreated successfully');
      } catch (e2) {
        print('Failed to recreate settings box: $e2');
      }
    }

    // Initialize simple reminder service
    try {
      await SimpleReminderService.init();
      print('Simple reminder service initialized successfully');
    } catch (e) {
      print('Error initializing simple reminder service: $e');
    }
    
    print('Hive initialized successfully with minimal setup');
  } catch (e) {
    print('Error initializing Hive: $e');
  }
  
  runApp(const PharmatoxApp());
}

class PharmatoxApp extends StatelessWidget {
  const PharmatoxApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Pharmatox',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF4FC3A1)),
        useMaterial3: true,
        fontFamily: 'Roboto',
      ),
      home: const OnboardingScreen(),
    );
  }
}

// ...existing code...

// ...existing code...

// ...existing code...


